image: ruby:2.2.5

pages:
  stage: deploy
  script:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-paginate
  - gem install jemoji
  - jekyll build -d public/
  artifacts:
    paths:
    - public
